###
POST http://192.168.50.1:6502/v1/api/epaper/line HTTP/1.1
content-type: application/json

{"colour":4,"positionx":[100,100],"positiony":[200,200]}
// red
###
POST http://192.168.50.1:6502/v1/api/epaper/line HTTP/1.1
content-type: application/json

{"colour":0,"positionx":[0,0],"positiony":[100,100]}
// black
###
POST http://192.168.50.1:6502/v1/api/epaper/circle HTTP/1.1
content-type: application/json

{"colour":0,"position":[200,200],"radius":100}
###
POST http://192.168.50.1:6502/v1/api/epaper/circle HTTP/1.1
content-type: application/json

{"colour":4,"position":[200,200],"radius":100, "fill":true}
###
POST http://192.168.50.1:6502/v1/api/epaper/rectangle HTTP/1.1
content-type: application/json

{"colour":0,"position":[0,0],"height":100,"wide":100}
###
POST http://192.168.50.1:6502/v1/api/epaper/rectangle HTTP/1.1
content-type: application/json

{"colour":0,"position":[0,0],"height":100,"wide":100,"fill":true}
###
POST http://192.168.50.1:6502/v1/api/epaper/point HTTP/1.1
content-type: application/json

{"colour":0,"position":[0,0]}

###
POST https://192.168.50.1:6502/v1/api/epaper/string HTTP/1.1
content-type: application/json

{"colour":0,"position":[10,10],"content":"test string", "font":24}

###
POST http://192.168.50.1:6502/v1/api/epaper/string HTTP/1.1
content-type: application/json

{"colour":0,"position":[0,0],"content":"我我我测试", "font":48}
###
POST http://192.168.50.1:6502/v1/api/epaper/image HTTP/1.1
content-type: application/json

{"imagepath":"/home/pi/test.bmp","position":[0,0]}



###
POST http://192.168.50.1:6502/v1/api/epaper/group HTTP/1.1
content-type: application/json

[
  {"rotate": 1},
  {
    "rectangle": {
      "colour": 4,
      "fill": true,
      "height": 30,
      "position": [
        0,
        0
      ],
      "wide": 640
    }
  },
  {
    "rectangle": {
      "colour": 4,
      "fill": true,
      "height": 30,
      "position": [
        0,
        200
      ],
      "wide": 640
    }
  },
  {
    "string": {
      "colour": 3,
      "content": "---Max's inprogress list---",
      "font": 24,
      "position": [
        20,
        3
      ]
    }
  },
  {
    "string": {
      "colour": 3,
      "content": "---Max's to do list---",
      "font": 24,
      "position": [
        20,
        203
      ]
    }
  },
  {
    "string": {
      "colour": 0,
      "content": "1. FC000958 estimation",
      "font": 24,
      "position": [
        20,
        40
      ]
    }
  },
  {
    "string": {
      "colour": 0,
      "content": "2. ML code jam",
      "font": 24,
      "position": [
        20,
        70
      ]
    }
  },
  {
    "string": {
      "colour": 0,
      "content": "3. ",
      "font": 24,
      "position": [
        20,
        100
      ]
    }
  },
  {
    "string": {
      "colour": 0,
      "content": "4. ",
      "font": 24,
      "position": [
        20,
        130
      ]
    }
  },
  {
    "string": {
      "colour": 0,
      "content": "5. ",
      "font": 24,
      "position": [
        20,
        160
      ]
    }
  },
  {
    "string": {
      "colour": 0,
      "content": "1. js study",
      "font": 24,
      "position": [
        20,
        230
      ]
    }
  },
  {
    "string": {
      "colour": 0,
      "content": "2. ",
      "font": 24,
      "position": [
        20,
        260
      ]
    }
  },
  {
    "string": {
      "colour": 0,
      "content": "3. ",
      "font": 24,
      "position": [
        20,
        290
      ]
    }
  },
  {
    "string": {
      "colour": 0,
      "content": "4. ",
      "font": 24,
      "position": [
        20,
        320
      ]
    }
  },
  {
    "string": {
      "colour": 0,
      "content": "5. ",
      "font": 24,
      "position": [
        20,
        350
      ]
    }
  }
]


###
POST http://192.168.50.1:6502/v1/api/epaper/group HTTP/1.1
content-type: application/json

[{"image":{"imagepath":"/home/pi/test.bmp","position":[170,60]}},{"string":{"colour":0,"position":[180,0],"content":"本项目二维码", "font":48}}]
###
POST http://192.168.50.1:6502/v1/api/epaper/group HTTP/1.1
content-type: application/json

[{"string":{"colour":3,"bcolour":4,"position":[0,0],"content":"汉字测试 字号四十八", "font":48}},
{"string":{"colour":4,"bcolour":0,"position":[0,50],"content":"汉字测试 字号四十", "font":40}},
{"string":{"colour":4,"bcolour":3,"position":[0,100],"content":"汉字测试 字号三十二", "font":32}},
{"string":{"colour":0,"bcolour":4,"position":[0,150],"content":"汉字测试 字号二十四", "font":24}},
{"string":{"colour":0,"bcolour":3,"position":[0,200],"content":"汉字测试 字号十六", "font":16}},
{"string":{"colour":3,"bcolour":0,"position":[0,250],"content":"汉字测试 字号十四", "font":14}},
{"string":{"colour":0,"bcolour":4,"position":[0,300],"content":"汉字测试 字号十二", "font":12}}]