###
PATCH http://10.242.146.124:6502/v1/api/epaper/line HTTP/1.1
content-type: application/json

{"colour":4,"positionx":[200,200],"positiony":[400,400]}
// red
###
PATCH http://10.242.146.124:6502/v1/api/epaper/line HTTP/1.1
content-type: application/json

{"colour":0,"positionx":[0,0],"positiony":[100,100]}
// black
###
PATCH http://10.242.146.124:6502/v1/api/epaper/circle HTTP/1.1
content-type: application/json

{"colour":0,"position":[400,400],"radius":200}
###
PATCH http://10.242.146.124:6502/v1/api/epaper/circle HTTP/1.1
content-type: application/json

{"colour":4,"position":[600,400],"radius":100, "fill":true}
###
PATCH http://10.242.146.124:6502/v1/api/epaper/rectangle HTTP/1.1
content-type: application/json

{"colour":0,"position":[0,0],"height":100,"wide":100}
###
PATCH http://10.242.146.124:6502/v1/api/epaper/rectangle HTTP/1.1
content-type: application/json

{
  "colour": 0,
  "fill": true,
  "height": 100,
  "position": [
    0,
    0
  ],
  "wide": 100
}
###
PATCH http://10.242.146.124:6502/v1/api/epaper/point HTTP/1.1
content-type: application/json

{
  "colour": 0,
  "position": [
    0,
    0
  ]
}

###
PATCH http://10.242.146.124:6502/v1/api/epaper/string HTTP/1.1
content-type: application/json

{
  "colour": 0,
  "content": "test string",
  "font": 8,
  "position": [
    10,
    10
  ]
}
###
PATCH http://10.242.146.124:6502/v1/api/epaper/string HTTP/1.1
content-type: application/json

{
  "colour": 0,
  "content": "test string",
  "font": 24,
  "position": [
    200,
    200
  ]
}
###
PATCH http://10.242.146.124:6502/v1/api/epaper/group HTTP/1.1
content-type: application/json

[
  {
    "string": {
      "colour": 0,
      "content": "test string",
      "font": 24,
      "position": [
        400,
        200
      ]
    }
  },
  {
    "point": {
      "colour": 0,
      "position": [
        100,
        100
      ]
    }
  },
  {
    "rectangle": {
      "colour": 0,
      "fill": true,
      "height": 100,
      "position": [
        0,
        0
      ],
      "wide": 100
    }
  },
  {
    "circle": {
      "colour": 4,
      "fill": true,
      "position": [
        200,
        200
      ],
      "radius": 100
    }
  },
  {
    "line": {
      "colour": 4,
      "positionx": [
        100,
        100
      ],
      "positiony": [
        400,
        400
      ]
    }
  }
]
### 
PATCH http://10.242.146.124:6502/v1/api/epaper/group HTTP/1.1
content-type: application/json

[
  {"rotate":0},
  {
    "string": {
      "colour": 0,
      "content": "test string",
      "font": 24,
      "position": [
        100,
        100
      ]
    }
  },
  {
    "point": {
      "colour": 0,
      "position": [
        100,
        100
      ]
    }
  },
  {
    "rectangle": {
      "colour": 0,
      "fill": true,
      "height": 100,
      "position": [
        0,
        0
      ],
      "wide": 100
    }
  },
  {
    "circle": {
      "colour": 4,
      "fill": true,
      "position": [
        200,
        200
      ],
      "radius": 100
    }
  },
  {
    "line": {
      "colour": 4,
      "positionx": [
        100,
        100
      ],
      "positiony": [
        400,
        400
      ]
    }
  }
]